---
name: Super-Linter

on: push

jobs:
  super-lint:
    name: Super-Linter
    runs-on:
      - self-hosted
      - Primary
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          # Testing multiple folders and files
          # I don't think this will work but I'm not sure how else to add multiple folders / files
          # Might have to do some more researching on this
          FILTER_REGEX_EXCLUDE: .*2022-2023/.*
          FILTER_REGEX_EXCLUDE: .*2022-2023/.*
          DEFAULT_BRANCH: Workflows-test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
