name: WPILib Build Test

on: push

jobs:
    build-latest:
        runs-on:
            - self-hosted
            - Primary
        steps:
            # Check out the code so the action can use it
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: WPILib Build 2023-2024
            # Set the working directory so gradlew and WPILib are in the right folder
              working-directory: ./2023-2024/main-bot
            # Run gradlew to build the robot code with java home being what it is set to during manual runtime
            # This machine should have Java 17 installed which is what WPILib is using for building with 2024
              run: ./gradlew build
    build-2022-2023:
        runs-on:
            - self-hosted
            - Primary
        steps:
            # Check out the code so the action can use it
            - name: Checkout code
              uses: actions/checkout@v4

            - name: WPILib Build 2022-2023
              working-directory: ./2022-2023/main-bot
              run: ./gradlew build
            

# I have no idea if this will work but this is just to test to see if it's possible and to get used to using actions
